/* SPDX-License-Identifier: BSD-3-Clause */

#ifndef RTE_FLOW_CMD_PARSER_PRIV_H
#define RTE_FLOW_CMD_PARSER_PRIV_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include <rte_flow.h>

#ifdef __cplusplus
extern "C" {
#endif

struct rte_flow_cmd_parse_ctx;

/* Parser token indices shared between rte_flow parser core and testpmd. */
enum index {

	/* Special tokens. */
	ZERO = 0,
	END,
	START_SET,
	END_SET,

	/* Common tokens. */
	COMMON_INTEGER,
	COMMON_UNSIGNED,
	COMMON_PREFIX,
	COMMON_BOOLEAN,
	COMMON_STRING,
	COMMON_HEX,
	COMMON_FILE_PATH,
	COMMON_MAC_ADDR,
	COMMON_IPV4_ADDR,
	COMMON_IPV6_ADDR,
	COMMON_RULE_ID,
	COMMON_PORT_ID,
	COMMON_GROUP_ID,
	COMMON_PRIORITY_LEVEL,
	COMMON_INDIRECT_ACTION_ID,
	COMMON_PROFILE_ID,
	COMMON_POLICY_ID,
	COMMON_FLEX_HANDLE,
	COMMON_FLEX_TOKEN,
	COMMON_PATTERN_TEMPLATE_ID,
	COMMON_ACTIONS_TEMPLATE_ID,
	COMMON_TABLE_ID,
	COMMON_QUEUE_ID,
	COMMON_METER_COLOR_NAME,

	/* TOP-level command. */
	ADD,

	/* Top-level command. */
	SET,
	/* Sub-leve commands. */
	SET_RAW_ENCAP,
	SET_RAW_DECAP,
	SET_RAW_INDEX,
	SET_SAMPLE_ACTIONS,
	SET_SAMPLE_INDEX,
	SET_IPV6_EXT_REMOVE,
	SET_IPV6_EXT_PUSH,
	SET_IPV6_EXT_INDEX,

	/* Top-level command. */
	FLOW,
	/* Sub-level commands. */
	INFO,
	CONFIGURE,
	PATTERN_TEMPLATE,
	ACTIONS_TEMPLATE,
	TABLE,
	FLOW_GROUP,
	INDIRECT_ACTION,
	VALIDATE,
	CREATE,
	DESTROY,
	UPDATE,
	FLUSH,
	DUMP,
	QUERY,
	LIST,
	AGED,
	ISOLATE,
	TUNNEL,
	FLEX,
	QUEUE,
	PUSH,
	PULL,
	HASH,

	/* Flex arguments */
	FLEX_ITEM_CREATE,
	FLEX_ITEM_DESTROY,

	/* Pattern template arguments. */
	PATTERN_TEMPLATE_CREATE,
	PATTERN_TEMPLATE_DESTROY,
	PATTERN_TEMPLATE_CREATE_ID,
	PATTERN_TEMPLATE_DESTROY_ID,
	PATTERN_TEMPLATE_RELAXED_MATCHING,
	PATTERN_TEMPLATE_INGRESS,
	PATTERN_TEMPLATE_EGRESS,
	PATTERN_TEMPLATE_TRANSFER,
	PATTERN_TEMPLATE_SPEC,

	/* Actions template arguments. */
	ACTIONS_TEMPLATE_CREATE,
	ACTIONS_TEMPLATE_DESTROY,
	ACTIONS_TEMPLATE_CREATE_ID,
	ACTIONS_TEMPLATE_DESTROY_ID,
	ACTIONS_TEMPLATE_INGRESS,
	ACTIONS_TEMPLATE_EGRESS,
	ACTIONS_TEMPLATE_TRANSFER,
	ACTIONS_TEMPLATE_SPEC,
	ACTIONS_TEMPLATE_MASK,

	/* Queue arguments. */
	QUEUE_CREATE,
	QUEUE_DESTROY,
	QUEUE_FLOW_UPDATE_RESIZED,
	QUEUE_UPDATE,
	QUEUE_AGED,
	QUEUE_INDIRECT_ACTION,

	/* Queue create arguments. */
	QUEUE_CREATE_POSTPONE,
	QUEUE_TEMPLATE_TABLE,
	QUEUE_PATTERN_TEMPLATE,
	QUEUE_ACTIONS_TEMPLATE,
	QUEUE_RULE_ID,

	/* Queue destroy arguments. */
	QUEUE_DESTROY_ID,
	QUEUE_DESTROY_POSTPONE,

	/* Queue update arguments. */
	QUEUE_UPDATE_ID,

	/* Queue indirect action arguments */
	QUEUE_INDIRECT_ACTION_CREATE,
	QUEUE_INDIRECT_ACTION_LIST_CREATE,
	QUEUE_INDIRECT_ACTION_UPDATE,
	QUEUE_INDIRECT_ACTION_DESTROY,
	QUEUE_INDIRECT_ACTION_QUERY,
	QUEUE_INDIRECT_ACTION_QUERY_UPDATE,

	/* Queue indirect action create arguments */
	QUEUE_INDIRECT_ACTION_CREATE_ID,
	QUEUE_INDIRECT_ACTION_INGRESS,
	QUEUE_INDIRECT_ACTION_EGRESS,
	QUEUE_INDIRECT_ACTION_TRANSFER,
	QUEUE_INDIRECT_ACTION_CREATE_POSTPONE,
	QUEUE_INDIRECT_ACTION_SPEC,
	QUEUE_INDIRECT_ACTION_LIST,

	/* Queue indirect action update arguments */
	QUEUE_INDIRECT_ACTION_UPDATE_POSTPONE,

	/* Queue indirect action destroy arguments */
	QUEUE_INDIRECT_ACTION_DESTROY_ID,
	QUEUE_INDIRECT_ACTION_DESTROY_POSTPONE,

	/* Queue indirect action query arguments */
	QUEUE_INDIRECT_ACTION_QUERY_POSTPONE,

	/* Queue indirect action query_update arguments */
	QUEUE_INDIRECT_ACTION_QU_MODE,

	/* Push arguments. */
	PUSH_QUEUE,

	/* Pull arguments. */
	PULL_QUEUE,

	/* Table arguments. */
	TABLE_CREATE,
	TABLE_DESTROY,
	TABLE_RESIZE,
	TABLE_RESIZE_COMPLETE,
	TABLE_CREATE_ID,
	TABLE_DESTROY_ID,
	TABLE_RESIZE_ID,
	TABLE_RESIZE_RULES_NUMBER,
	TABLE_INSERTION_TYPE,
	TABLE_INSERTION_TYPE_NAME,
	TABLE_HASH_FUNC,
	TABLE_HASH_FUNC_NAME,
	TABLE_GROUP,
	TABLE_PRIORITY,
	TABLE_INGRESS,
	TABLE_EGRESS,
	TABLE_TRANSFER,
	TABLE_TRANSFER_WIRE_ORIG,
	TABLE_TRANSFER_VPORT_ORIG,
	TABLE_RESIZABLE,
	TABLE_RULES_NUMBER,
	TABLE_PATTERN_TEMPLATE,
	TABLE_ACTIONS_TEMPLATE,

	GROUP_ID,
	GROUP_INGRESS,
	GROUP_EGRESS,
	GROUP_TRANSFER,
	GROUP_SET_MISS_ACTIONS,

	HASH_CALC_TABLE,
	HASH_CALC_PATTERN_INDEX,
	HASH_CALC_PATTERN,
	HASH_CALC_ENCAP,
	HASH_CALC_DEST,
	ENCAP_HASH_FIELD_SRC_PORT,
	ENCAP_HASH_FIELD_GRE_FLOW_ID,

	TUNNEL_CREATE,
	TUNNEL_CREATE_TYPE,
	TUNNEL_LIST,
	TUNNEL_DESTROY,
	TUNNEL_DESTROY_ID,

	DESTROY_RULE,
	DESTROY_IS_USER_ID,

	QUERY_ACTION,
	QUERY_IS_USER_ID,

	LIST_GROUP,

	AGED_DESTROY,

	VC_GROUP,
	VC_PRIORITY,
	VC_INGRESS,
	VC_EGRESS,
	VC_TRANSFER,
	VC_TUNNEL_SET,
	VC_TUNNEL_MATCH,
	VC_USER_ID,
	VC_IS_USER_ID,

	DUMP_ALL,
	DUMP_ONE,
	DUMP_IS_USER_ID,

	CONFIG_QUEUES_NUMBER,
	CONFIG_QUEUES_SIZE,
	CONFIG_COUNTERS_NUMBER,
	CONFIG_AGING_OBJECTS_NUMBER,
	CONFIG_METERS_NUMBER,
	CONFIG_CONN_TRACK_NUMBER,
	CONFIG_QUOTAS_NUMBER,
	CONFIG_FLAGS,
	CONFIG_HOST_PORT,

	INDIRECT_ACTION_CREATE,
	INDIRECT_ACTION_LIST_CREATE,
	INDIRECT_ACTION_FLOW_CONF_CREATE,
	INDIRECT_ACTION_UPDATE,
	INDIRECT_ACTION_DESTROY,
	INDIRECT_ACTION_QUERY,
	INDIRECT_ACTION_QUERY_UPDATE,

	INDIRECT_ACTION_CREATE_ID,
	INDIRECT_ACTION_INGRESS,
	INDIRECT_ACTION_EGRESS,
	INDIRECT_ACTION_TRANSFER,
	INDIRECT_ACTION_SPEC,
	INDIRECT_ACTION_LIST,
	INDIRECT_ACTION_FLOW_CONF,

	INDIRECT_ACTION_DESTROY_ID,

	INDIRECT_ACTION_QU_MODE,
	INDIRECT_ACTION_QU_MODE_NAME,

	ITEM_PATTERN,
	ITEM_PARAM_IS,
	ITEM_PARAM_SPEC,
	ITEM_PARAM_LAST,
	ITEM_PARAM_MASK,
	ITEM_PARAM_PREFIX,
	ITEM_NEXT,
	ITEM_END,
	ITEM_VOID,
	ITEM_INVERT,
	ITEM_ANY,
	ITEM_ANY_NUM,
	ITEM_PORT_ID,
	ITEM_PORT_ID_ID,
	ITEM_MARK,
	ITEM_MARK_ID,
	ITEM_RAW,
	ITEM_RAW_RELATIVE,
	ITEM_RAW_SEARCH,
	ITEM_RAW_OFFSET,
	ITEM_RAW_LIMIT,
	ITEM_RAW_PATTERN,
	ITEM_RAW_PATTERN_HEX,
	ITEM_ETH,
	ITEM_ETH_DST,
	ITEM_ETH_SRC,
	ITEM_ETH_TYPE,
	ITEM_ETH_HAS_VLAN,
	ITEM_VLAN,
	ITEM_VLAN_TCI,
	ITEM_VLAN_PCP,
	ITEM_VLAN_DEI,
	ITEM_VLAN_VID,
	ITEM_VLAN_INNER_TYPE,
	ITEM_VLAN_HAS_MORE_VLAN,
	ITEM_IPV4,
	ITEM_IPV4_VER_IHL,
	ITEM_IPV4_TOS,
	ITEM_IPV4_LENGTH,
	ITEM_IPV4_ID,
	ITEM_IPV4_FRAGMENT_OFFSET,
	ITEM_IPV4_TTL,
	ITEM_IPV4_PROTO,
	ITEM_IPV4_SRC,
	ITEM_IPV4_DST,
	ITEM_IPV6,
	ITEM_IPV6_TC,
	ITEM_IPV6_FLOW,
	ITEM_IPV6_LEN,
	ITEM_IPV6_PROTO,
	ITEM_IPV6_HOP,
	ITEM_IPV6_SRC,
	ITEM_IPV6_DST,
	ITEM_IPV6_HAS_FRAG_EXT,
	ITEM_IPV6_ROUTING_EXT,
	ITEM_IPV6_ROUTING_EXT_TYPE,
	ITEM_IPV6_ROUTING_EXT_NEXT_HDR,
	ITEM_IPV6_ROUTING_EXT_SEG_LEFT,
	ITEM_ICMP,
	ITEM_ICMP_TYPE,
	ITEM_ICMP_CODE,
	ITEM_ICMP_IDENT,
	ITEM_ICMP_SEQ,
	ITEM_UDP,
	ITEM_UDP_SRC,
	ITEM_UDP_DST,
	ITEM_TCP,
	ITEM_TCP_SRC,
	ITEM_TCP_DST,
	ITEM_TCP_FLAGS,
	ITEM_SCTP,
	ITEM_SCTP_SRC,
	ITEM_SCTP_DST,
	ITEM_SCTP_TAG,
	ITEM_SCTP_CKSUM,
	ITEM_VXLAN,
	ITEM_VXLAN_VNI,
	ITEM_VXLAN_FLAG_G,
	ITEM_VXLAN_FLAG_VER,
	ITEM_VXLAN_FLAG_I,
	ITEM_VXLAN_FLAG_P,
	ITEM_VXLAN_FLAG_B,
	ITEM_VXLAN_FLAG_O,
	ITEM_VXLAN_FLAG_D,
	ITEM_VXLAN_FLAG_A,
	ITEM_VXLAN_GBP_ID,
	ITEM_VXLAN_GPE_PROTO,
	ITEM_VXLAN_FIRST_RSVD,
	ITEM_VXLAN_SECND_RSVD,
	ITEM_VXLAN_THIRD_RSVD,
	ITEM_VXLAN_LAST_RSVD,
	ITEM_E_TAG,
	ITEM_E_TAG_GRP_ECID_B,
	ITEM_NVGRE,
	ITEM_NVGRE_TNI,
	ITEM_MPLS,
	ITEM_MPLS_LABEL,
	ITEM_MPLS_TC,
	ITEM_MPLS_S,
	ITEM_MPLS_TTL,
	ITEM_GRE,
	ITEM_GRE_PROTO,
	ITEM_GRE_C_RSVD0_VER,
	ITEM_GRE_C_BIT,
	ITEM_GRE_K_BIT,
	ITEM_GRE_S_BIT,
	ITEM_FUZZY,
	ITEM_FUZZY_THRESH,
	ITEM_GTP,
	ITEM_GTP_FLAGS,
	ITEM_GTP_MSG_TYPE,
	ITEM_GTP_TEID,
	ITEM_GTPC,
	ITEM_GTPU,
	ITEM_GENEVE,
	ITEM_GENEVE_VNI,
	ITEM_GENEVE_PROTO,
	ITEM_GENEVE_OPTLEN,
	ITEM_VXLAN_GPE,
	ITEM_VXLAN_GPE_VNI,
	ITEM_VXLAN_GPE_PROTO_IN_DEPRECATED_VXLAN_GPE_HDR,
	ITEM_VXLAN_GPE_FLAGS,
	ITEM_VXLAN_GPE_RSVD0,
	ITEM_VXLAN_GPE_RSVD1,
	ITEM_ARP_ETH_IPV4,
	ITEM_ARP_ETH_IPV4_SHA,
	ITEM_ARP_ETH_IPV4_SPA,
	ITEM_ARP_ETH_IPV4_THA,
	ITEM_ARP_ETH_IPV4_TPA,
	ITEM_IPV6_EXT,
	ITEM_IPV6_EXT_NEXT_HDR,
	ITEM_IPV6_FRAG_EXT,
	ITEM_IPV6_FRAG_EXT_NEXT_HDR,
	ITEM_IPV6_FRAG_EXT_FRAG_DATA,
	ITEM_IPV6_FRAG_EXT_ID,
	ITEM_ICMP6,
	ITEM_ICMP6_TYPE,
	ITEM_ICMP6_CODE,
	ITEM_ICMP6_ECHO_REQUEST,
	ITEM_ICMP6_ECHO_REQUEST_ID,
	ITEM_ICMP6_ECHO_REQUEST_SEQ,
	ITEM_ICMP6_ECHO_REPLY,
	ITEM_ICMP6_ECHO_REPLY_ID,
	ITEM_ICMP6_ECHO_REPLY_SEQ,
	ITEM_ICMP6_ND_NS,
	ITEM_ICMP6_ND_NS_TARGET_ADDR,
	ITEM_ICMP6_ND_NA,
	ITEM_ICMP6_ND_NA_TARGET_ADDR,
	ITEM_ICMP6_ND_OPT,
	ITEM_ICMP6_ND_OPT_TYPE,
	ITEM_ICMP6_ND_OPT_SLA_ETH,
	ITEM_ICMP6_ND_OPT_SLA_ETH_SLA,
	ITEM_ICMP6_ND_OPT_TLA_ETH,
	ITEM_ICMP6_ND_OPT_TLA_ETH_TLA,
	ITEM_META,
	ITEM_META_DATA,
	ITEM_RANDOM,
	ITEM_RANDOM_VALUE,
	ITEM_GRE_KEY,
	ITEM_GRE_KEY_VALUE,
	ITEM_GRE_OPTION,
	ITEM_GRE_OPTION_CHECKSUM,
	ITEM_GRE_OPTION_KEY,
	ITEM_GRE_OPTION_SEQUENCE,
	ITEM_GTP_PSC,
	ITEM_GTP_PSC_QFI,
	ITEM_GTP_PSC_PDU_T,
	ITEM_PPPOES,
	ITEM_PPPOED,
	ITEM_PPPOE_SEID,
	ITEM_PPPOE_PROTO_ID,
	ITEM_PPPOE_PROTO_ID_SESSION_ID,
	ITEM_PPPOE_PROTO_ID_PROTO_ID,
	ITEM_HIGIG2,
	ITEM_HIGIG2_CLASSIFICATION,
	ITEM_HIGIG2_VID,
	ITEM_TAG,
	ITEM_TAG_DATA,
	ITEM_TAG_INDEX,
	ITEM_L2TPV3OIP,
	ITEM_L2TPV3OIP_SESSION_ID,
	ITEM_ESP,
	ITEM_ESP_SPI,
	ITEM_ESP_SEQ_NUM,
	ITEM_AH,
	ITEM_AH_SPI,
	ITEM_AH_SEQ_NUM,
	ITEM_PFCP,
	ITEM_PFCP_S_FIELD,
	ITEM_PFCP_SEID,
	ITEM_PFCP_SI,
	ITEM_PFCP_MSG_TYPE,
	ITEM_PFCP_SEQUENCE,
	ITEM_ECPRI,
	ITEM_ECPRI_COMMON,
	ITEM_ECPRI_COMMON_TYPE,
	ITEM_ECPRI_COMMON_TYPE_IQ_DATA,
	ITEM_ECPRI_COMMON_TYPE_RTC_CTRL,
	ITEM_ECPRI_COMMON_TYPE_DLY_MSR,
	ITEM_ECPRI_MSG_IQ_DATA_PCID,
	ITEM_ECPRI_MSG_RTC_CTRL_RTCID,
	ITEM_ECPRI_MSG_DLY_MSR_MSRID,
	ITEM_GENEVE_OPT,
	ITEM_GENEVE_OPT_CLASS,
	ITEM_GENEVE_OPT_TYPE,
	ITEM_GENEVE_OPT_LENGTH,
	ITEM_GENEVE_OPT_LEN,
	ITEM_GENEVE_OPT_DATA,
	ITEM_INTEGRITY,
	ITEM_INTEGRITY_LEVEL,
	ITEM_INTEGRITY_VALUE,
	ITEM_CONNTRACK,
	ITEM_POL_PORT,
	ITEM_POL_METER,
	ITEM_POL_POLICY,
	ITEM_PORT_REPRESENTOR,
	ITEM_PORT_REPRESENTOR_PORT_ID,
	ITEM_REPRESENTED_PORT,
	ITEM_REPRESENTED_PORT_PORT_ID,
	ITEM_REPRESENTED_PORT_ETHDEV_PORT_ID,
	ITEM_FLEX,
	ITEM_FLEX_HANDLE,
	ITEM_FLEX_DATA,
	ITEM_FLEX_TUNNEL,
	ITEM_FLEX_META,
	ITEM_FLEX_META_VALUE,
	ITEM_FLEX_ITEM_HANDLE,
	ITEM_FLEX_PATTERN_HANDLE,
	ITEM_L2TPV2,
	ITEM_L2TPV2_TYPE,
	ITEM_L2TPV2_LENGTH,
	ITEM_L2TPV2_TUNNEL_ID,
	ITEM_L2TPV2_SESSION_ID,
	ITEM_L2TPV2_NS,
	ITEM_L2TPV2_NR,
	ITEM_L2TPV2_OFFSET,
	ITEM_L2TPV2_TYPE_DATA,
	ITEM_L2TPV2_TYPE_DATA_L,
	ITEM_L2TPV2_TYPE_DATA_S,
	ITEM_L2TPV2_TYPE_DATA_O,
	ITEM_L2TPV2_TYPE_DATA_L_S,
	ITEM_L2TPV2_TYPE_CTRL,
	ITEM_L2TPV2_MSG_DATA_TUNNEL_ID,
	ITEM_L2TPV2_MSG_DATA_SESSION_ID,
	ITEM_L2TPV2_MSG_DATA_L_LENGTH,
	ITEM_L2TPV2_MSG_DATA_L_TUNNEL_ID,
	ITEM_L2TPV2_MSG_DATA_L_SESSION_ID,
	ITEM_L2TPV2_MSG_DATA_S_TUNNEL_ID,
	ITEM_L2TPV2_MSG_DATA_S_SESSION_ID,
	ITEM_L2TPV2_MSG_DATA_S_NS,
	ITEM_L2TPV2_MSG_DATA_S_NR,
	ITEM_L2TPV2_MSG_DATA_O_TUNNEL_ID,
	ITEM_L2TPV2_MSG_DATA_O_SESSION_ID,
	ITEM_L2TPV2_MSG_DATA_O_OFFSET,
	ITEM_L2TPV2_MSG_DATA_L_S_LENGTH,
	ITEM_L2TPV2_MSG_DATA_L_S_TUNNEL_ID,
	ITEM_L2TPV2_MSG_DATA_L_S_SESSION_ID,
	ITEM_L2TPV2_MSG_DATA_L_S_NS,
	ITEM_L2TPV2_MSG_DATA_L_S_NR,
	ITEM_L2TPV2_MSG_CTRL_LENGTH,
	ITEM_L2TPV2_MSG_CTRL_TUNNEL_ID,
	ITEM_L2TPV2_MSG_CTRL_SESSION_ID,
	ITEM_L2TPV2_MSG_CTRL_NS,
	ITEM_L2TPV2_MSG_CTRL_NR,
	ITEM_PPP,
	ITEM_PPP_ADDR,
	ITEM_PPP_CTRL,
	ITEM_PPP_PROTO_ID,
	ITEM_METER,
	ITEM_METER_POLICY_ID,
	ITEM_METER_COLOR,
	ITEM_QUOTA,
	ITEM_QUOTA_ID,
	ITEM_QUOTA_STATE,
	ITEM_QUOTA_STATE_NAME,
	ITEM_AGGR_AFFINITY,
	ITEM_AGGR_AFFINITY_INDEX,
	ITEM_AGGR_AFFINITY_VALUE,
	ITEM_TX_QUEUE,
	ITEM_TX_QUEUE_INDEX,
	ITEM_TX_QUEUE_VALUE,
	ITEM_IB_BTH,
	ITEM_IB_BTH_OPCODE,
	ITEM_IB_BTH_DST_QP,
	ITEM_IB_BTH_PKEY,
	ITEM_IB_BTH_QP_TYPE,
	ITEM_IB_BTH_DST_QPN,
	ITEM_IB_BTH_PSN,
	ITEM_IPV6_PUSH_REMOVE_EXT,
	ITEM_IPV6_PUSH_REMOVE_EXT_TYPE,
	ITEM_PTYPE,
	ITEM_PTYPE_ID,
	ITEM_PTYPE_VALUE,
	ITEM_NSH,
	ITEM_NSH_TTL,
	ITEM_NSH_MDTYPE,
	ITEM_NSH_NEXT_PROTO,
	ITEM_NSH_METADATA,
	ITEM_COMPARE,
	ITEM_COMPARE_OP,
	ITEM_COMPARE_OP_VALUE,
	ITEM_COMPARE_FIELD_A_TYPE,
	ITEM_COMPARE_FIELD_A_TYPE_VALUE,
	ITEM_COMPARE_FIELD_A_LEVEL,
	ITEM_COMPARE_FIELD_A_LEVEL_VALUE,
	ITEM_COMPARE_FIELD_A_TAG_INDEX,
	ITEM_COMPARE_FIELD_A_TYPE_ID,
	ITEM_COMPARE_FIELD_A_CLASS_ID,
	ITEM_COMPARE_FIELD_A_OFFSET,
	ITEM_COMPARE_FIELD_B_TYPE,
	ITEM_COMPARE_FIELD_B_TYPE_VALUE,
	ITEM_COMPARE_LVALUE,
	ITEM_COMPARE_RVALUE,
	ITEM_COMPARE_RVALUE_MASK,
	ITEM_COMPARE_MASK,
	ITEM_COMPARE_FIELD_B_LEVEL,
	ITEM_COMPARE_FIELD_B_LEVEL_VALUE,
	ITEM_COMPARE_FIELD_B_TAG_INDEX,
	ITEM_COMPARE_FIELD_B_TYPE_ID,
	ITEM_COMPARE_FIELD_B_CLASS_ID,
	ITEM_COMPARE_FIELD_B_OFFSET,
	ITEM_COMPARE_FIELD_B_VALUE,
	ITEM_COMPARE_FIELD_B_POINTER,
	ITEM_COMPARE_FIELD_WIDTH,

	/* Validate/create actions. */
	ACTIONS,
	ACTION_NEXT,
	ACTION_END,
	ACTION_VOID,
	ACTION_PASSTHRU,
	ACTION_SKIP_CMAN,
	ACTION_JUMP,
	ACTION_JUMP_GROUP,
	ACTION_MARK,
	ACTION_MARK_ID,
	ACTION_FLAG,
	ACTION_QUEUE,
	ACTION_QUEUE_INDEX,
	ACTION_DROP,
	ACTION_COUNT,
	ACTION_COUNT_ID,
	ACTION_RSS,
	ACTION_RSS_FUNC,
	ACTION_RSS_LEVEL,
	ACTION_RSS_FUNC_DEFAULT,
	ACTION_RSS_FUNC_TOEPLITZ,
	ACTION_RSS_FUNC_SIMPLE_XOR,
	ACTION_RSS_FUNC_SYMMETRIC_TOEPLITZ,
	ACTION_RSS_TYPES,
	ACTION_RSS_TYPE,
	ACTION_RSS_KEY,
	ACTION_RSS_KEY_LEN,
	ACTION_RSS_QUEUES,
	ACTION_RSS_QUEUE,
	ACTION_PF,
	ACTION_VF,
	ACTION_VF_ORIGINAL,
	ACTION_VF_ID,
	ACTION_PORT_ID,
	ACTION_PORT_ID_ORIGINAL,
	ACTION_PORT_ID_ID,
	ACTION_METER,
	ACTION_METER_COLOR,
	ACTION_METER_COLOR_TYPE,
	ACTION_METER_COLOR_GREEN,
	ACTION_METER_COLOR_YELLOW,
	ACTION_METER_COLOR_RED,
	ACTION_METER_ID,
	ACTION_METER_MARK,
	ACTION_METER_MARK_CONF,
	ACTION_METER_MARK_CONF_COLOR,
	ACTION_METER_PROFILE,
	ACTION_METER_PROFILE_ID2PTR,
	ACTION_METER_POLICY,
	ACTION_METER_POLICY_ID2PTR,
	ACTION_METER_COLOR_MODE,
	ACTION_METER_STATE,
	ACTION_OF_DEC_NW_TTL,
	ACTION_OF_POP_VLAN,
	ACTION_OF_PUSH_VLAN,
	ACTION_OF_PUSH_VLAN_ETHERTYPE,
	ACTION_OF_SET_VLAN_VID,
	ACTION_OF_SET_VLAN_VID_VLAN_VID,
	ACTION_OF_SET_VLAN_PCP,
	ACTION_OF_SET_VLAN_PCP_VLAN_PCP,
	ACTION_OF_POP_MPLS,
	ACTION_OF_POP_MPLS_ETHERTYPE,
	ACTION_OF_PUSH_MPLS,
	ACTION_OF_PUSH_MPLS_ETHERTYPE,
	ACTION_VXLAN_ENCAP,
	ACTION_VXLAN_DECAP,
	ACTION_NVGRE_ENCAP,
	ACTION_NVGRE_DECAP,
	ACTION_L2_ENCAP,
	ACTION_L2_DECAP,
	ACTION_MPLSOGRE_ENCAP,
	ACTION_MPLSOGRE_DECAP,
	ACTION_MPLSOUDP_ENCAP,
	ACTION_MPLSOUDP_DECAP,
	ACTION_SET_IPV4_SRC,
	ACTION_SET_IPV4_SRC_IPV4_SRC,
	ACTION_SET_IPV4_DST,
	ACTION_SET_IPV4_DST_IPV4_DST,
	ACTION_SET_IPV6_SRC,
	ACTION_SET_IPV6_SRC_IPV6_SRC,
	ACTION_SET_IPV6_DST,
	ACTION_SET_IPV6_DST_IPV6_DST,
	ACTION_SET_TP_SRC,
	ACTION_SET_TP_SRC_TP_SRC,
	ACTION_SET_TP_DST,
	ACTION_SET_TP_DST_TP_DST,
	ACTION_MAC_SWAP,
	ACTION_DEC_TTL,
	ACTION_SET_TTL,
	ACTION_SET_TTL_TTL,
	ACTION_SET_MAC_SRC,
	ACTION_SET_MAC_SRC_MAC_SRC,
	ACTION_SET_MAC_DST,
	ACTION_SET_MAC_DST_MAC_DST,
	ACTION_INC_TCP_SEQ,
	ACTION_INC_TCP_SEQ_VALUE,
	ACTION_DEC_TCP_SEQ,
	ACTION_DEC_TCP_SEQ_VALUE,
	ACTION_INC_TCP_ACK,
	ACTION_INC_TCP_ACK_VALUE,
	ACTION_DEC_TCP_ACK,
	ACTION_DEC_TCP_ACK_VALUE,
	ACTION_RAW_ENCAP,
	ACTION_RAW_DECAP,
	ACTION_RAW_ENCAP_SIZE,
	ACTION_RAW_ENCAP_INDEX,
	ACTION_RAW_ENCAP_INDEX_VALUE,
	ACTION_RAW_DECAP_INDEX,
	ACTION_RAW_DECAP_INDEX_VALUE,
	ACTION_SET_TAG,
	ACTION_SET_TAG_DATA,
	ACTION_SET_TAG_INDEX,
	ACTION_SET_TAG_MASK,
	ACTION_SET_META,
	ACTION_SET_META_DATA,
	ACTION_SET_META_MASK,
	ACTION_SET_IPV4_DSCP,
	ACTION_SET_IPV4_DSCP_VALUE,
	ACTION_SET_IPV6_DSCP,
	ACTION_SET_IPV6_DSCP_VALUE,
	ACTION_AGE,
	ACTION_AGE_TIMEOUT,
	ACTION_AGE_UPDATE,
	ACTION_AGE_UPDATE_TIMEOUT,
	ACTION_AGE_UPDATE_TOUCH,
	ACTION_SAMPLE,
	ACTION_SAMPLE_RATIO,
	ACTION_SAMPLE_INDEX,
	ACTION_SAMPLE_INDEX_VALUE,
	ACTION_INDIRECT,
	ACTION_INDIRECT_LIST,
	ACTION_INDIRECT_LIST_HANDLE,
	ACTION_INDIRECT_LIST_CONF,
	INDIRECT_LIST_ACTION_ID2PTR_HANDLE,
	INDIRECT_LIST_ACTION_ID2PTR_CONF,
	ACTION_SHARED_INDIRECT,
	INDIRECT_ACTION_PORT,
	INDIRECT_ACTION_ID2PTR,
	ACTION_MODIFY_FIELD,
	ACTION_MODIFY_FIELD_OP,
	ACTION_MODIFY_FIELD_OP_VALUE,
	ACTION_MODIFY_FIELD_DST_TYPE,
	ACTION_MODIFY_FIELD_DST_TYPE_VALUE,
	ACTION_MODIFY_FIELD_DST_LEVEL,
	ACTION_MODIFY_FIELD_DST_LEVEL_VALUE,
	ACTION_MODIFY_FIELD_DST_TAG_INDEX,
	ACTION_MODIFY_FIELD_DST_TYPE_ID,
	ACTION_MODIFY_FIELD_DST_CLASS_ID,
	ACTION_MODIFY_FIELD_DST_OFFSET,
	ACTION_MODIFY_FIELD_SRC_TYPE,
	ACTION_MODIFY_FIELD_SRC_TYPE_VALUE,
	ACTION_MODIFY_FIELD_SRC_LEVEL,
	ACTION_MODIFY_FIELD_SRC_LEVEL_VALUE,
	ACTION_MODIFY_FIELD_SRC_TAG_INDEX,
	ACTION_MODIFY_FIELD_SRC_TYPE_ID,
	ACTION_MODIFY_FIELD_SRC_CLASS_ID,
	ACTION_MODIFY_FIELD_SRC_OFFSET,
	ACTION_MODIFY_FIELD_SRC_VALUE,
	ACTION_MODIFY_FIELD_SRC_POINTER,
	ACTION_MODIFY_FIELD_WIDTH,
	ACTION_CONNTRACK,
	ACTION_CONNTRACK_UPDATE,
	ACTION_CONNTRACK_UPDATE_DIR,
	ACTION_CONNTRACK_UPDATE_CTX,
	ACTION_POL_G,
	ACTION_POL_Y,
	ACTION_POL_R,
	ACTION_PORT_REPRESENTOR,
	ACTION_PORT_REPRESENTOR_PORT_ID,
	ACTION_REPRESENTED_PORT,
	ACTION_REPRESENTED_PORT_ETHDEV_PORT_ID,
	ACTION_SEND_TO_KERNEL,
	ACTION_QUOTA_CREATE,
	ACTION_QUOTA_CREATE_LIMIT,
	ACTION_QUOTA_CREATE_MODE,
	ACTION_QUOTA_CREATE_MODE_NAME,
	ACTION_QUOTA_QU,
	ACTION_QUOTA_QU_LIMIT,
	ACTION_QUOTA_QU_UPDATE_OP,
	ACTION_QUOTA_QU_UPDATE_OP_NAME,
	ACTION_IPV6_EXT_REMOVE,
	ACTION_IPV6_EXT_REMOVE_INDEX,
	ACTION_IPV6_EXT_REMOVE_INDEX_VALUE,
	ACTION_IPV6_EXT_PUSH,
	ACTION_IPV6_EXT_PUSH_INDEX,
	ACTION_IPV6_EXT_PUSH_INDEX_VALUE,
	ACTION_NAT64,
	ACTION_NAT64_MODE,
	ACTION_JUMP_TO_TABLE_INDEX,
	ACTION_JUMP_TO_TABLE_INDEX_TABLE,
	ACTION_JUMP_TO_TABLE_INDEX_TABLE_VALUE,
	ACTION_JUMP_TO_TABLE_INDEX_INDEX,
};

/** Maximum number of stacked tokens/arguments tracked by the parser. */
#define CTX_STACK_SIZE 16

/** Parser context shared between rte_flow parser core and testpmd. */
struct rte_flow_cmd_parse_ctx {
	const enum index *next[CTX_STACK_SIZE];
	const void *args[CTX_STACK_SIZE];
	enum index curr;
	enum index prev;
	int next_num;
	int args_num;
	uint32_t eol:1;
	uint32_t last:1;
	uint16_t port;
	uint32_t objdata;
	void *object;
	void *objmask;
};

static inline const struct arg *
rte_flow_cmd_parse_ctx_pop_arg(struct rte_flow_cmd_parse_ctx *ctx)
{
	if (!ctx || !ctx->args_num)
		return NULL;
	return ctx->args[--ctx->args_num];
}

static inline int
rte_flow_cmd_parse_ctx_push_arg(struct rte_flow_cmd_parse_ctx *ctx,
				      const struct arg *arg)
{
	if (!ctx || ctx->args_num == CTX_STACK_SIZE)
		return -1;
	ctx->args[ctx->args_num++] = arg;
	return 0;
}

static inline const enum index *
rte_flow_cmd_parse_ctx_peek_next(const struct rte_flow_cmd_parse_ctx *ctx)
{
	if (!ctx || !ctx->next_num)
		return NULL;
	return ctx->next[ctx->next_num - 1];
}

static inline const enum index *
rte_flow_cmd_parse_ctx_pop_next(struct rte_flow_cmd_parse_ctx *ctx)
{
	if (!ctx || !ctx->next_num)
		return NULL;
	return ctx->next[--ctx->next_num];
}

static inline int
rte_flow_cmd_parse_ctx_push_next(struct rte_flow_cmd_parse_ctx *ctx,
			      const enum index *next)
{
	if (!ctx || !next || ctx->next_num >= CTX_STACK_SIZE)
		return -1;
	ctx->next[ctx->next_num++] = next;
	return 0;
}

static inline int
rte_flow_cmd_parse_ctx_replace_next(struct rte_flow_cmd_parse_ctx *ctx,
			          unsigned int index_from_end,
			          const enum index *next)
{
	if (!ctx || !next)
		return -1;
	if (index_from_end >= (unsigned int)ctx->next_num)
		return -1;
	ctx->next[ctx->next_num - 1 - index_from_end] = next;
	return 0;
}

static inline void
rte_flow_cmd_parse_ctx_reset(struct rte_flow_cmd_parse_ctx *ctx)
{
	if (!ctx)
		return;
	memset(ctx->next, 0, sizeof(ctx->next));
	memset(ctx->args, 0, sizeof(ctx->args));
	ctx->curr = ZERO;
	ctx->prev = ZERO;
	ctx->next_num = 0;
	ctx->args_num = 0;
	ctx->eol = 0;
	ctx->last = 0;
	ctx->port = 0;
	ctx->objdata = 0;
	ctx->object = NULL;
	ctx->objmask = NULL;
}

/* Token argument metadata shared by parser implementations. */
struct arg {
	uint32_t hton:1;
	uint32_t sign:1;
	uint32_t bounded:1;
	uintmax_t min;
	uintmax_t max;
	uint32_t offset;
	uint32_t size;
	const uint8_t *mask;
};

/* Parser token definition shared between rte_flow library and testpmd. */
struct token {
	const char *type;
	const char *help;
	const void *priv;
	const enum index *const *next;
	const struct arg *const *args;
	int (*call)(struct rte_flow_cmd_parse_ctx *ctx, const struct token *token,
		   const char *str, unsigned int len,
		   void *buf, unsigned int size);
	int (*comp)(struct rte_flow_cmd_parse_ctx *ctx, const struct token *token,
		    unsigned int ent, char *buf, unsigned int size);
	const char *name;
};

/* Helper macros used to build token graphs. */
#define NEXT(...) (const enum index *const []){ __VA_ARGS__, NULL, }
#define NEXT_ENTRY(...) (const enum index []){ __VA_ARGS__, ZERO, }
#define ARGS(...) (const struct arg *const []){ __VA_ARGS__, NULL, }
#define ARGS_ENTRY(s, f) \
	(&(const struct arg){ \
		.offset = offsetof(s, f), \
		.size = sizeof(((s *)0)->f), \
	})

#define ARGS_ENTRY_BF(s, f, b) \
	(&(const struct arg){ \
		.size = sizeof(s), \
		.mask = (const void *)&(const s){ .f = (1 << (b)) - 1 }, \
	})

#define ARGS_ENTRY_BOUNDED(s, f, i, a) \
	(&(const struct arg){ \
		.bounded = 1, \
		.min = (i), \
		.max = (a), \
		.offset = offsetof(s, f), \
		.size = sizeof(((s *)0)->f), \
	})

#define ARGS_ENTRY_MASK(s, f, m) \
	(&(const struct arg){ \
		.offset = offsetof(s, f), \
		.size = sizeof(((s *)0)->f), \
		.mask = (const void *)(m), \
	})

#define ARGS_ENTRY_MASK_HTON(s, f, m) \
	(&(const struct arg){ \
		.hton = 1, \
		.offset = offsetof(s, f), \
		.size = sizeof(((s *)0)->f), \
		.mask = (const void *)(m), \
	})

#define ARGS_ENTRY_PTR(s, f) \
	(&(const struct arg){ \
		.size = sizeof(*((s *)0)->f), \
	})

#define ARGS_ENTRY_ARB(o, s) \
	(&(const struct arg){ \
		.offset = (o), \
		.size = (s), \
	})

#define ARGS_ENTRY_ARB_BOUNDED(o, s, i, a) \
	(&(const struct arg){ \
		.bounded = 1, \
		.min = (i), \
		.max = (a), \
		.offset = (o), \
		.size = (s), \
	})

#define ARGS_ENTRY_HTON(s, f) \
	(&(const struct arg){ \
		.hton = 1, \
		.offset = offsetof(s, f), \
		.size = sizeof(((s *)0)->f), \
	})

#define ARG_ENTRY_HTON(s) \
	(&(const struct arg){ \
		.hton = 1, \
		.offset = 0, \
		.size = sizeof(s), \
	})

struct parse_item_priv {
	enum rte_flow_item_type type;
	uint32_t size;
};

struct parse_action_priv {
	enum rte_flow_action_type type;
	uint32_t size;
};

#define PRIV_ITEM(t, s) \
	(&(const struct parse_item_priv){ \
		.type = RTE_FLOW_ITEM_TYPE_ ## t, \
		.size = (s), \
	})

#define PRIV_ACTION(t, s) \
	(&(const struct parse_action_priv){ \
		.type = RTE_FLOW_ACTION_TYPE_ ## t, \
		.size = (s), \
	})

static inline int
rte_flow_cmd_parser_strcmp_partial(const char *full, const char *partial,
				       size_t partial_len)
{
	int ret;

	if (!full || !partial)
		return -1;
	ret = strncmp(full, partial, partial_len);
	if (ret)
		return ret;
	if (strlen(full) <= partial_len)
		return 0;
	return full[partial_len];
}

static inline int
rte_flow_cmd_parse_default(struct rte_flow_cmd_parse_ctx *ctx,
			     const struct token *token, const char *str,
			     unsigned int len, void *buf, unsigned int size)
{
	(void)ctx;
	(void)buf;
	(void)size;
	if (!token || !str)
		return -1;
	return rte_flow_cmd_parser_strcmp_partial(token->name, str, len) ?
		-1 : (int)len;
}

#ifdef __cplusplus
}
#endif

#endif /* RTE_FLOW_CMD_PARSER_PRIV_H */
